name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag adrgor/ebiznesbackend:latest
    - name: Push Docker image to repository
      run: docker push adrgor/ebiznesbackend:latest
